/*M!999999\- enable the sandbox mode */ 
-- MariaDB dump 10.19-12.0.2-MariaDB, for osx10.20 (arm64)
--
-- Host: localhost    Database: openaudit
-- ------------------------------------------------------
-- Server version	12.0.2-MariaDB

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*M!100616 SET @OLD_NOTE_VERBOSITY=@@NOTE_VERBOSITY, NOTE_VERBOSITY=0 */;

--
-- Table structure for table `widgets`
--

DROP TABLE IF EXISTS `widgets`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `widgets` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `org_id` int(10) unsigned NOT NULL DEFAULT 1,
  `description` text NOT NULL,
  `type` enum('line','pie','status','traffic','') DEFAULT 'line',
  `options` text NOT NULL,
  `sql` text NOT NULL,
  `link` text NOT NULL,
  `icon` varchar(50) NOT NULL DEFAULT '',
  `help_text` varchar(200) NOT NULL DEFAULT '',
  `primary_text` varchar(200) NOT NULL DEFAULT '',
  `secondary_text` varchar(200) NOT NULL DEFAULT '',
  `ternary_text` varchar(200) NOT NULL DEFAULT '',
  `where` varchar(50) NOT NULL DEFAULT '',
  `line_table` varchar(50) NOT NULL DEFAULT '',
  `line_event` varchar(50) NOT NULL DEFAULT '',
  `line_days` smallint(6) NOT NULL DEFAULT 0,
  `pie_column` varchar(50) NOT NULL DEFAULT '',
  `pie_limit` smallint(6) NOT NULL DEFAULT 0,
  `traffic_primary_query_id` smallint(6) NOT NULL DEFAULT 0,
  `traffic_secondary_query_id` smallint(6) NOT NULL DEFAULT 0,
  `traffic_ternary_query_id` smallint(6) NOT NULL DEFAULT 0,
  `status_secondary_sql` text NOT NULL,
  `status_primary_color` varchar(20) NOT NULL DEFAULT '',
  `status_secondary_color` varchar(20) NOT NULL DEFAULT '',
  `status_link_query_id` smallint(6) NOT NULL DEFAULT 0,
  `edited_by` varchar(200) NOT NULL DEFAULT '',
  `edited_date` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=71 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `widgets`
--

LOCK TABLES `widgets` WRITE;
/*!40000 ALTER TABLE `widgets` DISABLE KEYS */;
set autocommit=0;
INSERT INTO `widgets` VALUES (1,'New Devices Discovered per Day',1,'','line','','','devices?devices.first_seen=LIKE@date&properties=devices.id,devices.icon,devices.type,devices.os_group,devices.name,devices.domain,devices.ip,devices.identification,devices.manufacturer,devices.os_family,devices.status,devices.first_seen','','','Devices','','','','devices','create',30,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (2,'New Software Discovered per Day',1,'','line','','','devices?change_log.db_table=software&change_log.db_action=create&change_log.timestamp=LIKE@date&properties=devices.id,devices.icon,devices.ip,devices.name,devices.os_family,change_log.details,change_log.timestamp','','','Software','','','','software','create',30,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (3,'Devices Not Seen (0-180+ Days)',1,'','pie','','SELECT IF ( devices.last_seen = \'2000-01-01\', \'unknown\', ( IF ( devices.last_seen < DATE(NOW() - INTERVAL 180 day), \'180 Days or more\', ( IF ( devices.last_seen < DATE(NOW() - INTERVAL 150 day), \'150-180 days\', ( IF ( devices.last_seen < DATE(NOW() - INTERVAL 120 day), \'120-150 days\', ( IF ( devices.last_seen < DATE(NOW() - INTERVAL 90 day), \'90-120 days\', ( IF ( devices.last_seen < DATE(NOW() - INTERVAL 60 day), \'60-90 days\', ( IF ( devices.last_seen < DATE(NOW() - INTERVAL 30 day), \'30-60 days\', \'7-30 days\' ) ) ) ) ) ) ) ) ) ) ) ) ) AS `my_name`, IF ( devices.last_seen = \'2000-01-01\', \'devices.last_seen=\', ( IF ( devices.last_seen < DATE(NOW() - INTERVAL 180 day), CONCAT(\'devices.last_seen=<\', DATE(NOW() - INTERVAL 180 day)), ( IF ( devices.last_seen < DATE(NOW() - INTERVAL 150 day), CONCAT(\'devices.last_seen=>\', DATE(NOW() - INTERVAL 180 day), \'&devices.last_seen=<\', DATE(NOW() - INTERVAL 150 day)), ( IF ( devices.last_seen < DATE(NOW() - INTERVAL 120 day), CONCAT(\'devices.last_seen=>\', DATE(NOW() - INTERVAL 150 day), \'&devices.last_seen=<\', DATE(NOW() - INTERVAL 120 day)), ( IF ( devices.last_seen < DATE(NOW() - INTERVAL 90 day), CONCAT(\'devices.last_seen=>\', DATE(NOW() - INTERVAL 120 day), \'&devices.last_seen=<\', DATE(NOW() - INTERVAL 90 day)), ( IF ( devices.last_seen < DATE(NOW() - INTERVAL 60 day), CONCAT(\'devices.last_seen=>\', DATE(NOW() - INTERVAL 90 day), \'&devices.last_seen=<\', DATE(NOW() - INTERVAL 60 day)), ( IF ( devices.last_seen < DATE(NOW() - INTERVAL 30 day), CONCAT(\'devices.last_seen=>\', DATE(NOW() - INTERVAL 60 day), \'&devices.last_seen=<\', DATE(NOW() - INTERVAL 30 day)), CONCAT(\'devices.last_seen=>\', DATE(NOW() - INTERVAL 30 day), \'&devices.last_seen=<\', DATE(NOW() - INTERVAL 7 day))) ) ) ) ) ) ) ) ) ) ) ) ) AS `my_description`, count(devices.id) AS `count` FROM devices WHERE @filter AND DATE(devices.last_seen) < DATE(NOW() - INTERVAL 7 day) GROUP BY `my_name`','devices?@description&properties=devices.id,devices.type,devices.name,devices.ip,devices.os_family,devices.last_seen,devices.status','','','','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (4,'Devices by Type',1,'','pie','','','','','','','','','','','',0,'devices.type',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (5,'Devices by OS Family',1,'','pie','','','','','','','','','','','',0,'devices.os_family',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (6,'Devices by Manufacturer',1,'','pie','','','','','','','','','','','',0,'devices.manufacturer',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (7,'Software Keys',1,'','pie','','','devices?software_key.name=@name&properties=devices.id,devices.icon,devices.name,devices.domain,devices.ip,software_key.name,software_key.string','','','','','','','','',0,'software_key.name',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (8,'Devices by Status',1,'','pie','','','','','','','','','','','',0,'devices.status',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (9,'Devices by Function',1,'','pie','','','devices?devices.function=@name&properties=devices.id,devices.icon,devices.type,devices.os_group,devices.name,devices.domain,devices.ip,devices.os_family,devices.function,devices.status','','','','','','','','',0,'devices.function',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (10,'Servers',1,'','pie','','','devices?server.name=@name&properties=devices.id,devices.icon,devices.type,devices.os_group,devices.name,devices.domain,devices.ip,devices.os_family,server.name,server.version,server.version_string,server.port','','','','','','','','',0,'server.name',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (11,'End of Warranty (0-2+ Years)',1,'','pie','','SELECT if ( devices.warranty_expires = \'2000-01-01\', \'unknown\', ( if ( devices.warranty_expires < DATE(NOW()), \'expired\', ( if ( devices.warranty_expires > DATE(NOW() + INTERVAL 730 day), \'2 Years or more\', ( if ( devices.warranty_expires > DATE(NOW() + INTERVAL 365 day), \'1-2 years\', ( if ( devices.warranty_expires > DATE(NOW() + INTERVAL 270 day), \'270-365 days\', ( if ( devices.warranty_expires > DATE(NOW() + INTERVAL 180 day), \'180-270 days\', ( if ( devices.warranty_expires > DATE(NOW() + INTERVAL 90 day), \'90-180 days\', \'Less than 90 Days\' ) ) ) ) ) ) ) ) ) ) ) ) ) AS `my_name`, if ( devices.warranty_expires = \'2000-01-01\', \'devices.warranty_expires=2000-01-01\', ( if ( devices.warranty_expires < DATE(NOW()), CONCAT(\'devices.warranty_expires=<\', DATE(NOW())), ( if ( devices.warranty_expires > DATE(NOW() + INTERVAL 730 day), CONCAT(\'devices.warranty_expires=>\', DATE(NOW() + INTERVAL 730 day)), ( if ( devices.warranty_expires > DATE(NOW() + INTERVAL 365 day), CONCAT(\'devices.warranty_expires=<\', DATE(NOW() + INTERVAL 730 day), \'&devices.warranty_expires=>\', DATE(NOW() + INTERVAL 365 day)), ( if ( devices.warranty_expires > DATE(NOW() + INTERVAL 270 day), CONCAT(\'devices.warranty_expires=<\', DATE(NOW() + INTERVAL 365 day), \'&devices.warranty_expires=>\', DATE(NOW() + INTERVAL 270 day), \'&devices.warranty_expires=!=2000-01-01\'), ( if ( devices.warranty_expires > DATE(NOW() + INTERVAL 180 day), CONCAT(\'devices.warranty_expires=<\', DATE(NOW() + INTERVAL 270 day), \'&devices.warranty_expires=>\', DATE(NOW() + INTERVAL 180 day), \'&devices.warranty_expires=!=2000-01-01\'), ( if ( devices.warranty_expires > DATE(NOW() + INTERVAL 90 day), CONCAT(\'devices.warranty_expires=<\', DATE(NOW() + INTERVAL 180 day), \'&devices.warranty_expires=>\', DATE(NOW() + INTERVAL 90 day), \'&devices.warranty_expires=!=2000-01-01\'), CONCAT(\'devices.warranty_expires=<\', DATE(NOW() + INTERVAL 90 day), \'&devices.warranty_expires=>\', DATE(NOW()), \'&devices.warranty_expires=!=2000-01-01\' ) ) ) ) ) ) ) ) ) ) ) ) ) ) AS `my_description`, count(devices.id) AS `count` FROM devices WHERE @filter GROUP BY `my_name`','devices?devices.warranty_expires=!=2000-01-01&properties=devices.id,devices.icon,devices.type,devices.os_group,devices.name,devices.domain,devices.ip,devices.os_family,devices.warranty_expires','','','','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (12,'Devices by Class',1,'','pie','','','devices?devices.class=@name&properties=devices.id,devices.icon,devices.type,devices.os_group,devices.name,devices.domain,devices.ip,devices.os_family,devices.class,devices.status','','','','','','','','',0,'devices.class',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (13,'Devices by DNS Domain',1,'','pie','','','devices?devices.dns_domain=@name&properties=devices.id,devices.icon,devices.type,devices.os_group,devices.name,devices.dns_domain,devices.domain,devices.ip,devices.os_family,devices.os_group','','','','','','','','',0,'devices.dns_domain',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (14,'Devices by OS Group',1,'','pie','','','devices?devices.os_group=@name&properties=devices.id,devices.icon,devices.type,devices.os_group,devices.name,devices.domain,devices.ip,devices.os_family','','','','','','','','',0,'devices.os_group',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (15,'Devices by Location',1,'','pie','','SELECT locations.name as `name`, locations.id AS `description`, count(devices.id) AS `count` FROM locations LEFT JOIN devices ON (locations.id = devices.location_id) WHERE @filter GROUP BY locations.name, locations.id','devices?devices.location_id=@description&properties=devices.id,devices.icon,devices.type,devices.os_group,devices.name,devices.domain,devices.ip,devices.os_family,devices.location_id','','','','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (16,'Devices by Collector',1,'','pie','','SELECT IF (collectors.name IS NULL, \'localhost\', collectors.name) AS `my_name`, IF(collectors.uuid IS NULL, \'\', collectors.uuid) AS `description`, COUNT(devices.id) AS `count` FROM `devices` LEFT JOIN `collectors` ON (collectors.uuid = devices.collector_uuid) WHERE @filter GROUP BY `my_name`, collectors.uuid','devices?devices.collector_uuid=@description','','','','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (17,'Disk Manufacturers',1,'','pie','','','devices?disk.manufacturer=@name&properties=devices.id,devices.icon,devices.type,devices.os_group,devices.name,devices.domain,devices.ip,devices.os_group,disk.manufacturer,disk.model,disk.size','','','','','','','','',0,'disk.manufacturer',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (18,'Processor Models',1,'','pie','','','devices?processor.description=LIKE@name&properties=devices.id,devices.icon,devices.type,devices.os_group,devices.name,devices.ip,devices.os_group,devices.manufacturer,processor.description,processor.physical_count,processor.core_count,processor.logical_count','','','','','','','','',0,'processor.description',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (19,'Active Directory Sites',1,'','pie','','','devices?windows.client_site_name=@name&properties=devices.id,devices.icon,devices.os_group,devices.name,devices.ip,windows.client_site_name,windows.domain_controller_name,windows.active_directory_ou','','','','','','','','',0,'windows.client_site_name',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (20,'Active Directory OUs',1,'','pie','','','devices?windows.active_directory_ou=@name&properties=devices.id,devices.icon,devices.os_group,devices.name,devices.ip,windows.client_site_name,windows.domain_controller_name,windows.active_directory_ou','','','','','','','','',0,'windows.active_directory_ou',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (21,'Devices by Network',1,'','pie','','SELECT ip.network AS `my_name`, COUNT(ip.device_id) AS `count` FROM devices LEFT JOIN ip ON (devices.id = ip.device_id AND ip.current = \'y\') WHERE @filter AND ip.network != \'\' GROUP BY `my_name`','devices?ip.network=@name&properties=devices.id,devices.icon,devices.type,devices.os_group,devices.name,ip.ip,ip.mac,ip.network','','','','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (22,'Devices Audited per Day',1,'','line','','SELECT DATE(audit_log.timestamp) AS `date`, COUNT(DISTINCT audit_log.device_id) AS `count` FROM `audit_log` LEFT JOIN `devices` ON (audit_log.device_id = devices.id) WHERE DATE(audit_log.timestamp) >  DATE_SUB(CURDATE(), INTERVAL 30 DAY) GROUP BY DATE(audit_log.timestamp)','devices?audit_log.timestamp=like@date%&groupby=devices.id','','','Devices','','','','','',30,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (23,'End Of Life (0-90+ Days)',1,'','pie','','SELECT IF ( devices.end_of_life = \'2000-01-01\', \'Unknown\', ( IF ( devices.end_of_life < DATE(NOW()), \'Expired\', ( IF ( devices.end_of_life > DATE(NOW() + INTERVAL 90 day), \'90+ Days\', ( IF ( devices.end_of_life > DATE(NOW() + INTERVAL 60 day), \'60-90 Days\', ( IF ( devices.end_of_life > DATE(NOW() + INTERVAL 30 day), \'30-60 Days\', ( IF ( devices.end_of_life > DATE(NOW()), \'0-30 days\', \'Less than 30 Days\' ) ) ) ) ) ) ) ) ) ) ) AS `my_name`, IF ( devices.end_of_life = \'2000-01-01\', \'devices.end_of_life=2000-01-01\', ( IF ( devices.end_of_life < DATE(NOW()), CONCAT(\'devices.end_of_life=!=2000-01-01&devices.end_of_life=<\', DATE(NOW())), ( IF ( devices.end_of_life > DATE(NOW() + INTERVAL 90 day), CONCAT(\'devices.end_of_life=>\', DATE(NOW() + INTERVAL 90 day)), ( IF ( devices.end_of_life > DATE(NOW() + INTERVAL 60 day), CONCAT(\'devices.end_of_life=<\', DATE(NOW() + INTERVAL 90 day), \'&devices.end_of_life=>\', DATE(NOW() + INTERVAL 60 day)), ( IF ( devices.end_of_life > DATE(NOW() + INTERVAL 30 day), CONCAT(\'devices.end_of_life=<\', DATE(NOW() + INTERVAL 60 day), \'&devices.end_of_life=>\', DATE(NOW() + INTERVAL 30 day)), (  CONCAT(\'devices.end_of_life=<\', DATE(NOW() + INTERVAL 30 day), \'&devices.end_of_life=>\', DATE(NOW())) ) ) ) ) ) ) ) ) ) ) AS `my_description`,  count(devices.id) AS `count` FROM devices WHERE @filter GROUP BY `my_name`, `my_description`','devices?@description&properties=devices.id,devices.icon,devices.ip,devices.name,devices.os_family,devices.end_of_life,devices.status','','','Devices','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (24,'End of Service (0-90+ Days)',1,'','pie','','SELECT IF ( devices.end_of_service = \'2000-01-01\', \'Unknown\', ( IF ( devices.end_of_service < DATE(NOW()), \'Expired\', ( IF ( devices.end_of_service > DATE(NOW() + INTERVAL 90 day), \'90+ Days\', ( IF ( devices.end_of_service > DATE(NOW() + INTERVAL 60 day), \'60-90 Days\', ( IF ( devices.end_of_service > DATE(NOW() + INTERVAL 30 day), \'30-60 Days\', ( IF ( devices.end_of_service > DATE(NOW()), \'0-30 days\', \'Less than 30 Days\' ) ) ) ) ) ) ) ) ) ) ) AS `my_name`, IF ( devices.end_of_service = \'2000-01-01\', \'devices.end_of_service=2000-01-01\', ( IF ( devices.end_of_service < DATE(NOW()), CONCAT(\'devices.end_of_service=<\', DATE(NOW()), \'&devices.end_of_service=!=2000-01-01\'), ( IF ( devices.end_of_service > DATE(NOW() + INTERVAL 90 day), CONCAT(\'devices.end_of_service=>\', DATE(NOW() + INTERVAL 90 day)), ( IF ( devices.end_of_service > DATE(NOW() + INTERVAL 60 day), CONCAT(\'devices.end_of_service=<\', DATE(NOW() + INTERVAL 90 day), \'&devices.end_of_service=>\', DATE(NOW() + INTERVAL 60 day)), ( IF ( devices.end_of_service > DATE(NOW() + INTERVAL 30 day), CONCAT(\'devices.end_of_service=<\', DATE(NOW() + INTERVAL 60 day), \'&devices.end_of_service=>\', DATE(NOW() + INTERVAL 30 day)), ( CONCAT(\'devices.end_of_service=<\', DATE(NOW() + INTERVAL 30 day), \'&devices.end_of_service=>\', DATE(NOW())) ) ) ) ) ) ) ) ) ) ) AS `my_description`, count(devices.id) AS `count` FROM devices WHERE @filter GROUP BY `my_name`, `my_description`','devices?@description&properties=devices.id,devices.icon,devices.ip,devices.name,devices.os_family,devices.end_of_service,devices.status','','','Devices','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (25,'Device Age (0-3+ Years)',1,'','pie','','SELECT IF ( devices.purchase_date = \'2000-01-01\', \'unknown\', ( IF ( devices.purchase_date < DATE(NOW() - INTERVAL 3 year), \'3+ Years\', ( IF ( devices.purchase_date < DATE(NOW() - INTERVAL 2 year), \'2-3 Years\', ( IF ( devices.purchase_date < DATE(NOW() - INTERVAL 1 year), \'1-2 Years\', \'Less Than 1 Year\' ) ) ) ) ) ) ) AS `my_name`, IF ( devices.purchase_date = \'2000-01-01\', \'devices.purchase_date=2000-01-01\', ( IF ( devices.purchase_date < DATE(NOW() - INTERVAL 3 year), CONCAT(\'devices.purchase_date=<\', DATE(NOW() - INTERVAL 3 year), \"&devices.purchase_date=>2000-01-01\"), ( IF ( devices.purchase_date < DATE(NOW() - INTERVAL 2 year), CONCAT(\'devices.purchase_date=>\', DATE(NOW() - INTERVAL 3 year), \'&devices.purchase_date=<\', DATE(NOW() - INTERVAL 2 year)), ( IF ( devices.purchase_date < DATE(NOW() - INTERVAL 1 year), CONCAT(\'devices.purchase_date=>\', DATE(NOW() - INTERVAL 2 year), \'&devices.purchase_date=<\', DATE(NOW() - INTERVAL 1 year)), CONCAT(\'devices.purchase_date=>\', DATE(NOW() - INTERVAL 1 year)) ) ) ) ) ) ) ) AS `my_description`, count(devices.id) AS `count` FROM devices WHERE @filter GROUP BY `my_name`','devices?@description&properties=devices.id,devices.icon,devices.ip,devices.name,devices.os_family,devices.manufacturer,devices.os_family,devices.purchase_date,devices.status','','','Devices','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (26,'End of Lease (0-90+ Days)',1,'','pie','','SELECT IF ( devices.lease_expiry_date = \'2000-01-01\' OR devices.lease_expiry_date = \'0000-00-00\', \'Unknown\', ( IF ( devices.lease_expiry_date < DATE(NOW()), \'Expired\', ( IF ( devices.lease_expiry_date > DATE(NOW() + INTERVAL 90 day), \'90+ Days\', ( IF ( devices.lease_expiry_date > DATE(NOW() + INTERVAL 60 day), \'60-90 Days\', ( IF ( devices.lease_expiry_date > DATE(NOW() + INTERVAL 30 day), \'30-60 Days\', \'Less than 30 Days\' ) ) ) ) ) ) ) ) ) AS `my_name`, IF ( devices.lease_expiry_date = \'2000-01-01\' OR devices.lease_expiry_date = \'0000-00-00\', \'devices.lease_expiry_date=2000-01-01\', ( IF ( devices.lease_expiry_date < DATE(NOW()), CONCAT(\'devices.lease_expiry_date=<\', DATE(NOW()), \'&devices.lease_expiry_date=!=2000-01-01\'), ( IF ( devices.lease_expiry_date > DATE(NOW() + INTERVAL 90 day), CONCAT(\'devices.lease_expiry_date=>\', DATE(NOW() + INTERVAL 90 day)), ( IF ( devices.lease_expiry_date > DATE(NOW() + INTERVAL 60 day), CONCAT(\'devices.lease_expiry_date=<\', DATE(NOW() + INTERVAL 90 day), \'&devices.lease_expiry_date=>\', DATE(NOW() + INTERVAL 60 day)), ( IF ( devices.lease_expiry_date > DATE(NOW() + INTERVAL 30 day), CONCAT(\'devices.lease_expiry_date=<\', DATE(NOW() + INTERVAL 60 day), \'&devices.lease_expiry_date=>\', DATE(NOW() + INTERVAL 30 day)), ( CONCAT(\'devices.lease_expiry_date=<\', DATE(NOW() + INTERVAL 30 day), \'&devices.lease_expiry_date=>\', DATE(NOW())) ) ) ) ) ) ) ) ) ) ) AS `my_description`, count(devices.id) AS `count` FROM devices WHERE @filter GROUP BY `my_name`, `my_description`','devices?@description&properties=devices.id,devices.icon,devices.ip,devices.name,devices.os_family,devices.manufacturer,devices.os_family,devices.lease_expiry_date,devices.status','','','Devices','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (27,'Hardware Additions by Day',1,'Any items in the following tables that are new - bios, disk, memory, module, monitor, motherboard, network, optical, partition, processor, san, scsi, sound, video.','line','','SELECT DATE(`change_log`.`timestamp`) AS `date`, count(DATE(`change_log`.`timestamp` )) AS `count` FROM `change_log` LEFT JOIN `devices` ON (`devices`.`id` = `change_log`.`device_id`) WHERE @filter AND `change_log`.`timestamp` >= DATE_SUB(CURDATE(), INTERVAL 30 DAY) AND `change_log`.`db_table` IN (\'bios\', \'disk\', \'memory\', \'module\', \'monitor\', \'motherboard\', \'network\', \'optical\', \'partition\', \'processor\', \'san\', \'scsi\', \'sound\', \'video\') AND `change_log`.`db_action` = \'create\' GROUP BY DATE(`change_log`.`timestamp`)','devices?change_log.db_table=in(\'bios\',\'disk\',\'memory\',\'module\',\'monitor\',\'motherboard\',\'network\',\'optical\',\'partition\',;processor\',\'san\',\'scsi\',\'sound\',\'video\')&change_log.timestamp=like@date&change_log.db_action=create&properties=devices.id,devices.icon,devices.ip,devices.name,devices.os_family,change_log.details,change_log.timestamp','','','Devices','','','','devices','create',30,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (28,'Settings Additions by Day',1,'Any items in the following tables that are new - dns, file, ip, log, pagefile, print_queue, route, share, task, user, user_group, variable, vm, windows.','line','','SELECT DATE(`change_log`.`timestamp`) AS `date`, count(DATE(`change_log`.`timestamp` )) AS `count` FROM `change_log` LEFT JOIN `devices` ON (`devices`.`id` = `change_log`.`device_id`) WHERE @filter AND `change_log`.`timestamp` >= DATE_SUB(CURDATE(), INTERVAL 30 DAY) AND `change_log`.`db_table` IN (\'dns\', \'file\', \'ip\', \'log\', \'pagefile\', \'print_queue\', \'route\', \'share\', \'task\', \'user\', \'user_group\', \'variable\', \'vm\', \'windows\') AND `change_log`.`db_action` = \'create\' GROUP BY DATE(`change_log`.`timestamp`)','devices?change_log.db_table=in(\'dns\',\'file\',\'ip\',\'log\',\'pagefile\',\'print_queue\',\'route\',\'share\',\'task\',\'user\',\'user_group\',\'variable\',\'vm\',\'windows\')&change_log.timestamp=like@date&change_log.db_action=create&properties=devices.id,devices.icon,devices.ip,devices.name,devices.os_family,change_log.details,change_log.timestamp','','','Devices','','','','devices','create',30,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (29,'Software Additions by Day',1,'Any items in the following tables that are new - server, server_item, service, software, software_key.','line','','SELECT DATE(`change_log`.`timestamp`) AS `date`, count(DATE(`change_log`.`timestamp` )) AS `count` FROM `change_log` LEFT JOIN `devices` ON (`devices`.`id` = `change_log`.`device_id`) WHERE @filter AND `change_log`.`timestamp` >= DATE_SUB(CURDATE(), INTERVAL 30 DAY) AND `change_log`.`db_table` IN (\'server\', \'server_item\', \'service\', \'software\', \'software_key\') AND `change_log`.`db_action` = \'create\' GROUP BY DATE(`change_log`.`timestamp`)','devices?change_log.db_table=in(\'server\',\'server_item\',\'service\',\'software\',\'software_key\')&change_log.timestamp=like@date&change_log.db_action=create&properties=devices.id,devices.icon,devices.ip,devices.name,devices.os_family,change_log.details,change_log.timestamp','','','Devices','','','','devices','create',30,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (30,'Devices by Org',1,'Devies assigned by Org','pie','','SELECT orgs.name as `name`, orgs.id AS `description`, count(devices.id) AS `count` FROM orgs LEFT JOIN devices ON (orgs.id = devices.org_id) WHERE @filter GROUP BY orgs.name, orgs.id','devices?devices.org_id=@description','','','Devices','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (31,'Application Services',1,'Devices by defined Application','pie','','SELECT applications.name AS `my_name`, COUNT(application.device_id) AS `count`, applications.id AS `my_description` FROM applications LEFT JOIN application ON (applications.id = application.application_id) LEFT JOIN `devices` ON (application.device_id = devices.id) WHERE @filter GROUP BY `my_name`, applications.id','devices?application.application_id=@description','','','Devices','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (32,'Devices Not Seen (1-7+ Days)',1,'','pie','','SELECT IF ( DATE(devices.last_seen) = \'2000-01-01\', \'unknown\', ( IF ( DATE(devices.last_seen) < DATE(NOW() - INTERVAL 6 day), \'More than 7 Days\', ( IF ( DATE(devices.last_seen) = DATE(NOW() - INTERVAL 6 day), \'7 days\', ( IF ( DATE(devices.last_seen) = DATE(NOW() - INTERVAL 5 day), \'6 days\', ( IF ( DATE(devices.last_seen) = DATE(NOW() - INTERVAL 4 day), \'5 days\', ( IF ( DATE(devices.last_seen) = DATE(NOW() - INTERVAL 3 day), \'4 days\', ( IF ( DATE(devices.last_seen) = DATE(NOW() - INTERVAL 2 day), \'3 days\', ( IF ( DATE(devices.last_seen) = DATE(NOW() - INTERVAL 1 day), \'2 days\', ( IF ( DATE(devices.last_seen) = DATE(NOW() - INTERVAL 0 day), \'1 day\', \'\') ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) AS `my_name`, IF ( DATE(devices.last_seen) = \'2000-01-01\', \'devices.last_seen=2000-01-01\', ( IF ( DATE(devices.last_seen) < DATE(NOW() - INTERVAL 6 day), CONCAT(\'devices.last_seen=<\', DATE(NOW() - INTERVAL 6 day)), ( IF ( DATE(devices.last_seen) = DATE(NOW() - INTERVAL 6 day), CONCAT(\'devices.last_seen=LIKE\', DATE(NOW() - INTERVAL 6 day)), ( IF ( DATE(devices.last_seen) = DATE(NOW() - INTERVAL 5 day), CONCAT(\'devices.last_seen=LIKE\', DATE(NOW() - INTERVAL 5 day)), ( IF ( DATE(devices.last_seen) = DATE(NOW() - INTERVAL 4 day), CONCAT(\'devices.last_seen=LIKE\', DATE(NOW() - INTERVAL 4 day)), ( IF ( DATE(devices.last_seen) = DATE(NOW() - INTERVAL 3 day), CONCAT(\'devices.last_seen=LIKE\', DATE(NOW() - INTERVAL 3 day)), ( IF ( DATE(devices.last_seen) = DATE(NOW() - INTERVAL 2 day), CONCAT(\'devices.last_seen=LIKE\', DATE(NOW() - INTERVAL 2 day)), ( IF ( DATE(devices.last_seen) = DATE(NOW() - INTERVAL 1 day), CONCAT(\'devices.last_seen=LIKE\', DATE(NOW() - INTERVAL 1 day)), ( IF ( DATE(devices.last_seen) = DATE(NOW() - INTERVAL 0 day), CONCAT(\'devices.last_seen=LIKE\', DATE(NOW() - INTERVAL 0 day)), \'\' ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) AS `my_description`, count(devices.id) AS `count` FROM devices WHERE @filter GROUP BY `my_name`','devices?@description','','','Devices','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (33,'Devices by Cloud Type',1,'','pie','','','','','','Devices','','','devices.instance_provider != \'\'','','',0,'devices.instance_provider',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (34,'Devices per Cloud',1,'','pie','','SELECT clouds.name as `name`, clouds.id AS `description`, count(devices.id) AS `count` FROM clouds LEFT JOIN devices ON (clouds.id = devices.cloud_id) WHERE @filter AND devices.cloud_id IS NOT NULL GROUP BY clouds.name, clouds.id','devices?devices.cloud_id=@description&properties=devices.id,devices.icon,devices.type,devices.name,devices.domain,devices.ip,devices.os_family,devices.status,devices.instance_type,instance_state','','','Devices','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (35,'Devices by Cloud Network',1,'','pie','','SELECT IF(networks.name = networks.network, networks.network, CONCAT(networks.network, \' (\', networks.name, \')\')) as `name`, networks.network AS `description`, count(devices.id) AS `count` FROM networks LEFT JOIN ip ON (ip.network = networks.network and ip.current = \'y\') LEFT JOIN devices ON (ip.device_id = devices.id) WHERE @filter AND networks.options != \'\' GROUP BY networks.network, networks.name ORDER BY networks.network','devices?ip.network=@description&properties=devices.id,devices.icon,devices.type,devices.name,devices.domain,devices.ip,devices.os_family,devices.status,devices.instance_type,instance_state','','','Devices','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (36,'Devices by Cloud Region',1,'','pie','','SELECT CONCAT(clouds.type, \' - \', locations.name) as `name`, locations.id AS `description`, count(devices.id) AS `count` FROM locations LEFT JOIN devices ON (locations.id = devices.location_id) LEFT JOIN clouds ON (devices.cloud_id = clouds.id) WHERE @filter AND devices.cloud_id IS NOT NULL AND locations.type = \'Cloud\' GROUP BY devices.location_id, clouds.type','devices?devices.location_id=@description&properties=devices.id,devices.icon,devices.type,devices.name,devices.domain,devices.ip,devices.os_family,devices.status,devices.instance_type,instance_state','','','Devices','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (37,'Devices by Instance Type',1,'','pie','','SELECT CONCAT(clouds.type, \' - \', devices.instance_type) as `name`, devices.instance_type AS `description`, count(devices.id) AS `count` FROM devices LEFT JOIN clouds ON (devices.cloud_id = clouds.id) WHERE @filter AND devices.instance_type != \'\' GROUP BY devices.instance_type, clouds.type','devices?devices.instance_type=@description&properties=devices.id,devices.icon,devices.type,devices.name,devices.domain,devices.ip,devices.os_family,devices.status,devices.instance_type,instance_state','','','Devices','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (38,'Cloud Devices Audited per Day',1,'','line','','SELECT DATE(audit_log.timestamp) AS `date`, COUNT(DISTINCT audit_log.device_id) AS `count` FROM `audit_log` LEFT JOIN `devices` ON (audit_log.device_id = devices.id) WHERE @filter AND DATE(audit_log.timestamp) >  DATE_SUB(CURDATE(), INTERVAL 30 DAY) AND devices.cloud_id != \'\' GROUP BY DATE(audit_log.timestamp)','devices?audit_log.timestamp=like@date&properties=devices.id,devices.icon,devices.type,devices.name,devices.domain,devices.ip,devices.identification,devices.os_family,devices.status&groupby=audit_log.device_id&devices.cloud_id=!=','','','Devices','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (39,'Cloud Instances by Org and Type',1,'','pie','','SELECT CONCAT(orgs.name, \' - \', devices.instance_type) as `name`, CONCAT(devices.instance_type, \'&devices.org_id=\', orgs.id) AS `description`, count(devices.id) AS `count` FROM devices LEFT JOIN orgs ON (orgs.id = devices.org_id) WHERE @filter AND devices.cloud_id != \'\' GROUP BY devices.org_id, devices.instance_type','devices?devices.instance_type=@description&properties=devices.id,devices.icon,devices.type,devices.name,devices.domain,devices.ip,devices.os_family,devices.status,devices.instance_type,instance_state','','','Devices','','','','','',0,'',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (40,'Last Seen By',1,'','pie','','','devices?devices.last_seen_by=@name&properties=devices.id,devices.icon,devices.type,devices.os_group,devices.name,devices.domain,devices.ip,devices.identification,devices.manufacturer,devices.os_family,devices.last_seen_by,devices.status','','','Devices Last Seen By','','','','','',0,'devices.last_seen_by',0,0,0,0,'','','',0,'system','2000-01-01 00:00:00');
INSERT INTO `widgets` VALUES (41,'Windows Clients AntiVirus Status',1,'','traffic','','','','antivirus','','Windows 10 & 11','','','','','',0,'',0,48,49,47,'','','',0,'system','2001-01-01 00:00:00');
INSERT INTO `widgets` VALUES (42,'Windows Clients Firewall Status',1,'','traffic','','','','firewall','','Windows 10 & 11','','','','','',0,'',0,51,52,50,'','','',0,'system','2001-01-01 00:00:00');
INSERT INTO `widgets` VALUES (43,'Windows 11 Latest Build',1,'','traffic','','','','windows','','Without / With the latest Windows 11','','','','','',0,'',0,72,0,71,'','','',0,'system','2001-01-01 00:00:00');
INSERT INTO `widgets` VALUES (44,'Windows 10 Latest Build',1,'','traffic','','','','windows','','Without / With the latest Windows 10','','','','','',0,'',0,69,0,68,'','','',0,'system','2001-01-01 00:00:00');
INSERT INTO `widgets` VALUES (45,'Windows 2019 Server Latest Build',1,'','traffic','','','','windows','','Without / With the latest Windows 2019','','','','','',0,'',0,75,0,74,'','','',0,'system','2001-01-01 00:00:00');
INSERT INTO `widgets` VALUES (46,'Windows 2022 Server Latest Build',1,'','traffic','','','','windows','','Without / With the latest Windows 2022','','','','','',0,'',0,78,0,77,'','','',0,'system','2001-01-01 00:00:00');
INSERT INTO `widgets` VALUES (47,'Windows Server Firewall Status',1,'','traffic','','','','firewall','','Windows Server','','','','','',0,'',0,55,0,53,'','','',0,'system','2001-01-01 00:00:00');
INSERT INTO `widgets` VALUES (48,'Windows Server AntiVirus Status',1,'','traffic','','','','antivirus','','Windows Server','','','','','',0,'',0,56,0,54,'','','',0,'system','2001-01-01 00:00:00');
INSERT INTO `widgets` VALUES (49,'Software',1,'','traffic','','','','update','','Banned / Ignored / Approved','','','','','',0,'',0,57,59,58,'','','',0,'system','2001-01-01 00:00:00');
INSERT INTO `widgets` VALUES (50,'Windows Client Devices Without OS Updates',1,'','traffic','','','','update','','Windows 10 & 11, Last Checked For Updates > 2 weeks','','','','','',0,'',0,81,0,0,'','','',0,'system','2001-01-01 00:00:00');
INSERT INTO `widgets` VALUES (51,'Devices Not Seen for 30 / 7 / Less than 7 Days',1,'','traffic','','','','computer','','Not Seen for 30 / 7 / Less than 7 Days','','','','','',0,'',0,63,62,61,'','','',0,'system','2001-01-01 00:00:00');
INSERT INTO `widgets` VALUES (52,'Open Windows Shares',1,'','traffic','','','','folder','These shares can be written to by anyone without authentication.','Open Shares','Anyone can write here.','','','','',0,'',0,80,0,0,'','','',0,'admin','2025-11-19 19:04:50');
INSERT INTO `widgets` VALUES (53,'Windows Server Devices Without OS Updates',1,'','traffic','','','','update','','Windows 2019 & 2022, Last Checked For Updates > 2 weeks','','','','','',0,'',0,82,0,0,'','','',0,'system','2001-01-01 00:00:00');
INSERT INTO `widgets` VALUES (54,'Windows Devices Not Seen',1,'','traffic','','','','windows','','Not Seen for 30+, 7+ and less than 7 Days','','','','','',0,'',0,66,65,64,'','','',0,'system','2001-01-01 00:00:00');
INSERT INTO `widgets` VALUES (55,'Windows 2025 Server Latest Build',1,'','traffic','','','','windows','','Without / With the latest Windows 2025','','','','','',0,'',0,85,0,84,'','','',0,'system','2001-01-01 00:00:00');
INSERT INTO `widgets` VALUES (56,'Top 10 Vulnerable Devices',1,'','pie','','SELECT devices.id AS `description`, devices.name AS `name`, LENGTH(devices.cve) - LENGTH(REPLACE(devices.cve, \',\', \'\')) AS `count` FROM devices WHERE @filter AND devices.cve > \'\' ORDER BY `count` DESC LIMIT 10','devices?devices.id=@description','','','Top 10 Vulnerable Devices','','','','','',0,'bios.current',0,0,0,0,'','primary','',0,'admin','2025-11-19 16:18:40');
INSERT INTO `widgets` VALUES (57,'Top 10 Vendors of Vulnerabilities',1,'','pie','','SELECT vulnerabilities.vendor AS `description`, vulnerabilities.vendor AS `name`, COUNT(vulnerabilities.id) AS `count` FROM `vulnerabilities` LEFT JOIN `orgs` ON `vulnerabilities`.`org_id` = `orgs`.`id` WHERE @filter GROUP BY vulnerabilities.vendor ORDER BY `count` LIMIT 10','vulnerabilities?vulnerabilities.vendor=@description','','','Top 10 Vendors of Vulnerabilities','','','','','',0,'bios.current',0,0,0,0,'','primary','',0,'admin','2025-11-19 16:19:48');
INSERT INTO `widgets` VALUES (58,'Vulnerabilities Outstanding from Microsoft',1,'','pie','','SELECT vulnerabilities.base_severity AS `name`, COUNT(vulnerabilities_cache.vulnerability_id) AS `count`, \'\' AS `description` FROM vulnerabilities_cache LEFT JOIN vulnerabilities ON (vulnerabilities_cache.vulnerability_id = vulnerabilities.id) WHERE @filter AND vulnerabilities.vendor = \'microsoft\' GROUP BY base_severity','vulnerabilities?vulnerabilities.base_severity=@name&vulnerabilities.vendor=microsoft&count=>0','','','Vulnerabilities Outstanding from Microsoft','','','','','',0,'bios.current',0,0,0,0,'','primary','',0,'admin','2025-11-19 16:21:29');
INSERT INTO `widgets` VALUES (59,'Vulnerabilities By Severity',1,'','pie','','SELECT vulnerabilities.base_severity AS `name`, COUNT(vulnerabilities_cache.vulnerability_id) AS `count`, \'\' AS `description` FROM vulnerabilities_cache LEFT JOIN vulnerabilities ON (vulnerabilities_cache.vulnerability_id = vulnerabilities.id) WHERE @filter GROUP BY base_severity','vulnerabilities?vulnerabilities.base_severity=@name&count=>0','','','Vulnerabilities By Severity','','','','','',0,'bios.current',0,0,0,0,'','primary','',0,'admin','2025-11-19 16:23:09');
INSERT INTO `widgets` VALUES (60,'Windows Clients Without AntiVirus',1,'','status','','SELECT COUNT(devices.id) AS `count` FROM devices LEFT JOIN antivirus ON (devices.id = antivirus.device_id AND antivirus.current = \'y\') WHERE @filter AND antivirus.status IS NULL AND (devices.os_family LIKE \'Windows 10\' or devices.os_family LIKE \'Windows 11\') GROUP BY devices.id','','antivirus','Windows clients with no registered AntiVirus.','No AntiVirus','Windows Clients','','','','',0,'',0,0,0,0,'','danger','success',48,'admin','2025-11-19 16:28:47');
INSERT INTO `widgets` VALUES (61,'Windows 10 Not Latest Build',1,'','traffic','','','','windows','Windows 10 devices not running the latest release from Microsoft.','Not Latest Version','Windows 10','','','','',0,'',0,69,0,68,'','','',0,'admin','2025-11-19 19:39:18');
INSERT INTO `widgets` VALUES (62,'Windows 11 Not Latest Build',1,'','traffic','','','','windows','Windows 11 devices not running the latest release from Micsoroft.','Not Latest Version','Windows 11','','','','',0,'',0,72,0,71,'','','',0,'admin','2025-11-19 19:41:09');
INSERT INTO `widgets` VALUES (63,'Windows Clients Without Firewall',1,'','traffic','','','','firewall','Windows 10 and 11 machines without a registered Firewall','No Firewall','Windows Clients','','','','',0,'',0,51,52,50,'','','',0,'admin','2025-11-19 21:07:18');
INSERT INTO `widgets` VALUES (64,'Windows Clients Without OS Updates for more than 30 Days',1,'','status','','SELECT COUNT(devices.id) AS `count` FROM devices WHERE @filter AND devices.last_os_update < DATE(NOW() - INTERVAL 30 DAY) AND devices.last_os_update != \'\' AND devices.last_os_update != \'2000-01-01 00:00:00\' AND os_family IN (\'Windows 10\', \'Windows 11\')','','update','Windows 10 and 11 devices that have not been updated for 30 days or more.','No Updates','Windows Clients','','','','',0,'',0,0,0,0,'','danger','success',103,'admin','2025-11-19 20:57:49');
INSERT INTO `widgets` VALUES (65,'Windows Clients Not Seen for more than 30 Days',1,'','status','','SELECT COUNT(devices.id) AS `count` FROM devices WHERE @filter AND os_family IN (\'Windows 10\', \'Windows 11\') AND devices.last_seen < DATE(NOW() - INTERVAL 30 DAY)','','discoveries','Windows 10 and 11 devices not seen for 30 or more days.','Not Seen','Windows Clients','','','','',0,'',0,0,0,0,'','danger','success',105,'admin','2025-11-19 21:03:31');
INSERT INTO `widgets` VALUES (66,'Windows Server Without AntiVirus',1,'','status','','SELECT COUNT(devices.id) AS `count` FROM devices WHERE @filter AND devices.id NOT IN (SELECT devices.id FROM devices LEFT JOIN software ON (software.device_id = devices.id AND software.current = \'y\') RIGHT JOIN packages ON (software.name LIKE packages.software_name AND devices.os_group LIKE packages.os) WHERE devices.id IS NOT NULL AND packages.type = \'antivirus\' AND devices.os_name LIKE \'%Server%\') AND devices.os_name LIKE \'%Windows Server%\' GROUP BY devices.id','','antivirus','Windows Servers with no detected AntiVirus.','No AntiVirus','Windows Servers','','','','',0,'',0,0,0,0,'','danger','success',56,'admin','2025-11-19 21:06:21');
INSERT INTO `widgets` VALUES (67,'Windows Server Without Firewall',1,'','status','','SELECT COUNT(devices.id) AS `count` FROM devices WHERE @filter AND devices.id NOT IN (SELECT devices.id FROM devices LEFT JOIN software ON (software.device_id = devices.id AND software.current = \'y\') RIGHT JOIN packages ON (software.name LIKE packages.software_name AND devices.os_group LIKE packages.os) WHERE devices.id IS NOT NULL AND packages.type = \'firewall\' AND devices.os_name LIKE \'%Server%\') AND devices.os_name LIKE \'%Windows Server%\' GROUP BY devices.id','','firewall','Windows Servers with no detected Firewall.','No Firewall','Windows Servers','','','','',0,'',0,0,0,0,'','danger','success',55,'admin','2025-11-19 21:09:41');
INSERT INTO `widgets` VALUES (68,'Windows Server Not Latest Build',1,'','status','','SELECT COUNT(devices.id) AS `count` FROM devices LEFT JOIN windows ON (windows.device_id = devices.id AND windows.current = \'y\') WHERE @filter AND ((windows.build_number != \'14393.8594\' AND devices.os_family = \'Windows 2016\') OR (windows.build_number != \'17763.8027\' AND devices.os_family = \'Windows 2019\') OR (windows.build_number != \'20348.4405\' AND devices.os_family = \'Windows 2022\') OR (windows.build_number != \'26100.7171\' AND devices.os_family = \'Windows 2025\'))','','windows','Windows Servers not running the latest release from Microsoft.','Not Latest Version','Windows Servers','','','','',0,'',0,0,0,0,'','danger','success',98,'admin','2025-11-19 21:18:46');
INSERT INTO `widgets` VALUES (69,'Windows Servers Without OS Updates for more than 30 Days',1,'','status','','SELECT COUNT(devices.id) AS `count` FROM devices WHERE @filter AND devices.last_os_update < DATE(NOW() - INTERVAL 14 DAY) AND devices.last_os_update != \'\' AND devices.last_os_update != \'2000-01-01 00:00:00\' AND os_family IN (\'Windows 2016\', \'Windows 2019\', \'Windows 2022\', \'Windows 2025\')','','update','Windows Servers that have not been updated for 30 days or more.','No Updates','Windows Servers','','','','',0,'',0,0,0,0,'','danger','success',104,'admin','2025-11-19 21:20:45');
INSERT INTO `widgets` VALUES (70,'Windows Servers Not Seen for more than 30 Days',1,'','status','','SELECT COUNT(devices.id) AS `count` FROM devices WHERE @filter AND os_family IN (\'Windows 2016\', \'Windows 2019\', \'Windows 2022\', \'Windows 2025\') AND devices.last_seen < DATE(NOW() - INTERVAL 30 DAY)','','discoveries','Windows Servers not seen for 30 or more days.','Not Seen','Windows Servers','','','','',0,'',0,0,0,0,'','danger','success',106,'admin','2025-11-19 21:22:57');
/*!40000 ALTER TABLE `widgets` ENABLE KEYS */;
UNLOCK TABLES;
commit;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*M!100616 SET NOTE_VERBOSITY=@OLD_NOTE_VERBOSITY */;

-- Dump completed on 2025-11-19 21:26:19
